### ISSUE TITLE
Possible issues with how paths are used with the mod

### ISSUE THREAD

**Issue by FateUnix29** [Twofour2/IteratorKit#6]
Now, it could be just my oracle.json, but whenever I see this error I notice something peculiar..
It mysteriously changes from using Unix-style paths for *Windows* to using NTFS paths.
I have attached an image, and as I am playing as The Saint, I was able to mark it with my reticle as well.

The mod name is cut off, but that is all. After I changed the timer with devtools (alpha 9 key), it went away.

![ouch](https://github.com/Twofour2/IteratorKit/assets/157772455/c60cc261-2416-42e5-9c14-03524126284d)

**Comment by Twofour2** [comment]
this isn't an issue, windows can handle switching styles mid path just fine.
