### ISSUE TITLE
Mod doesn't seem to be working properly? Iterator wont spawn after multiple attempts.

### ISSUE THREAD

**Issue by AbyssalElegy** [Twofour2/IteratorKit#7]
I've verified that the mod is installed correctly, I've verified that Oracle.json is formatted correctly, the AI and Test rooms show up and work fine, but the test Iterator refuses to show up. No Umbilical rail, no puppet, no nothing. I've tried both the tutorials sample code and the other more recent sample code, I've tried unsubscribing and resubscribing to Iterator Kit, and I've even set up a modinfo.json file just in case that could somehow have something to do with it, all leading to nothing. The most the console log will tell me after warping to SU_AI is "An abstractCreature is trying to remove itself from room, but realizedCreature is remaining", though iterators aren't creatures so I'm not entirely sure it's related (I can't find my exception log but I'll continue looking after submitting this). Am I doing something wrong, do I just need to wait for an update, or does my pc have ghosts in it?

**Comment by Twofour2** [comment]
> I've verified that the mod is installed correctly, I've verified that Oracle.json 

The file name needs to be lowercase, and also not accidentally be ending with .txt (windows hides it)

Your mod also needs to be enabled in the remix menu

**Comment by AbyssalElegy** [comment]
> > I've verified that the mod is installed correctly, I've verified that Oracle.json
> 
> The file name needs to be lowercase, and also not accidentally be ending with .txt (windows hides it)
> 
> Your mod also needs to be enabled in the remix menu

oh my slug i may be stupid, thank you sir

**Comment by AbyssalElegy** [comment]
The file not being fully lowercase was in fact the issue! sorry if i wasted any time, and thank you
