### ISSUE TITLE
Big Problems

### ISSUE THREAD

**Issue by Willstuff1111** [Twofour2/IteratorKit#9]
Text will only appear whilst paused during the iterator dialouge

Game freezes everything exept text and pausing when in room with iterator

Edit:
Fixed

**Comment by Twofour2** [comment]
Can you send through some more details?
I.e.  Log files from the Rain World folder (consoleLog.txt, exceptionLog.txt)
your oracle.json
what other mods you have installed

also to answer your other question, you use `playerConversation` to run a dialog only on the first player encounter.

**Comment by Willstuff1111** [comment]
one other question before I send the files:

how do i add a custom prefix or at least a color for each line in a pearl dialouge

**Comment by Twofour2** [comment]
as stated in the docs: https://iteratorkit.twofour2.com/pearls.html#custom-dialog-colors
you add one of the prefixes to the start of the text.

**Comment by Willstuff1111** [comment]
Cusom as in blue for TC or something and other custom prefixes

**Comment by Willstuff1111** [comment]
Now it's just not spawning at all. I'll send the code file first
`[
  {
    "id": "TearingCoreOracle",
    "roomId": "SU_C04",
    "cornerPositions": [
      {
        "x": 10,
        "y": 33
      },
      {
        "x": 38,
        "y": 33
      },
      {
        "x": 38,
        "y": 3
      },
      {
        "x": 10,
        "y": 3
      }
    ],
      "body"
      :
      {
        "oracleColor": {
          "r": 239,
          "g": 194,
          "b": 255
        },
        "gown": {
          "color": {
            "type": "gradient",
            "from": {
              "r": 0,
              "g": 0,
              "b": 0
            },
            "to": {
              "r": 255,
              "g": 255,
              "b": 255
            }
          }
        },
        "sigil": null,
        "eyes": {
          "r": 255,
          "g": 0,
          "b": 0,
          "a": 255
        }
      },
      "roomEffects":
      {
        "pearls": "pebbles"
      },
      "events":
      {
        "generic": [
          {
            "event": "playerEnter",
            "random": true,
            "gravity": 1,
            "sound": "SS_AI_Exit_Work_Mode",
            "moveTo": {
              "x": 241,
              "y": 244
            },
            "texts": [ "..." ],
            "color": {
              "r": 0,
              "g": 0,
              "b": 255,
              "a": 255
            },
            "action": "giveMark"
          },
          {
            "event": "afterGiveMark",
            "for": [ "Red" ],
            "texts": [ "This is only avalible for red!" ],
            "action": "giveKarma",
            "actionParam": 9
          },
          {
            "event": "afterGiveMark",
            "for": [ "Red" ],
            "texts": [ "This is only avalible for red!" ]
          },
          {
            "event": "afterGiveMark",
            "action": "startPlayerConversation"
          },
          {
            "event": "playerConversation",
            "for": [ "Yellow", "White", "Red", "Gourmand", "Artificer" ],
            "hold": 4,
            "movement": "talk",
            "gravity": 1,
            "texts": [
              "...",
              "Are you hearing this?",
              "What are you, creature?",
              "Your genetic structure seems to be not native to my grounds...",
              "Wierd...",
              "I don't kno-......",
              "GET OUT!!!",
              "What???",
              "Sorry... I don't know what happened.",
              "You'd better leave. My condition is worsening.",
              "If you wish to help me... Cut off the link. My rot will consume everythi-...",
              "GET OUT OF HERE!!! I WILL KILL-",
              "Leave, now",
              "Before I kill you..."
            ],
            "color": {
              "r": 0,
              "g": 0,
              "b": 255,
              "a": 255
            }
          },
          {
            "event": "playerConversation",
            "gravity": 0
          }
        ]
      }
    
  }
]`

**Comment by Willstuff1111** [comment]
also, how do i make the gravity change from 1 to 0 at the end of a dialouge
